version: "3"

services:
  xornet-runner:
    build: .
    scale: 8
    environment:
      - TZ=Europe/Athens
      - ACCESS_TOKEN=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
      - ORGANIZATION=xornet-cloud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock